CREATE TABLE `todo` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(30) NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`dueDate` DATETIME NOT NULL,
	`done` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
